# Generated by Django 2.0.1 on 2018-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_checkproblem_current_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
