# Generated by Django 2.0.1 on 2018-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20180409_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='lemma',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
