# Generated by Django 2.0.1 on 2018-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20180421_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkproblem',
            name='current_status',
            field=models.TextField(default='Wrong'),
        ),
    ]
