# Generated by Django 2.0.1 on 2018-05-04 20:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('problems', '0010_auto_20180505_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='hashtag_list',
        ),
        migrations.AddField(
            model_name='problem',
            name='hashtag_list',
            field=models.ManyToManyField(blank=True, related_name='problem_hashtags', to='hashtags.Hashtag'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='problem',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None),
        ),
    ]
