# Generated by Django 2.0.1 on 2018-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20180505_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hashtag_list',
            field=models.ManyToManyField(related_name='problem_hashtags', to='hashtags.Hashtag'),
        ),
    ]
