# Generated by Django 2.0.1 on 2018-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20180505_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkproblem',
            name='current_input',
            field=models.TextField(default=''),
        ),
    ]
