# Generated by Django 2.0.1 on 2018-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_checkproblem_current_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkproblem',
            name='current_output',
            field=models.TextField(default=''),
        ),
    ]
