# Generated by Django 2.0.1 on 2018-04-09 16:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180407_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='detailed_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['AM-GM', '0'], ['divisibilty', '0']], size=None),
        ),
    ]
