# Generated by Django 2.0.1 on 2018-04-10 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180410_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inequalities_theory_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['AM-GM', '0'], ['Неравенство Коши', '0']], size=None),
        ),
    ]
