# Generated by Django 2.0.1 on 2018-04-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_inequalities_theory_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='inequalities_theory_skills',
            new_name='inequalities_skills',
        ),
    ]
