# Generated by Django 2.0.1 on 2018-05-17 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180411_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='function_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['Переменные', '0']], size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='polynom_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['ФСУ', '0'], ['Замена переменных', '0']], size=None),
        ),
    ]
