# Generated by Django 2.0.1 on 2018-05-17 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180518_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_theory_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=[['Четность', '0'], ['Делимость', '0'], ['Индукция', '0']], size=None),
        ),
    ]
